/*
 * DBFrame.java
 */
package database2019;

import java.sql.*;
import javax.swing.*;
import java.util.regex.*;

public class Classe_Di_Associazione extends DBFrame {

   public Classe_Di_Associazione() {
      super();
      initComponents();
      setModalita(INIZIO);
      setFrameTable(tabClasse_Di_Associazione);
      setNomeTabella("Classe_Di_Associazione");
   }

   /**
    * Imposta lo stato corrente del form. <br> In base allo stato vengono
    * abilitati o disabilitati alcuni oggetti del form.
    * 
    * @param modo intero che rappresenta lo stato
    */
   @Override
   final public void setModalita(int modo) {
      super.setModalita(modo);
      switch (modo) {
          case INIZIO:
            tIdAss.setEnabled (false);
            tNomeA.setEnabled(false);
            tCodice.setEnabled(false);
            break;
         case APPEND_QUERY:
            tIdAss.setEnabled (true);
            tNomeA.setEnabled(true);
            tCodice.setEnabled(true);
            break;
         case BROWSE:
            tIdAss.setEnabled (false);
            tNomeA.setEnabled(false);
            tCodice.setEnabled(false);
            break;
         case UPDATE:
             tIdAss.setEnabled (false);
            tNomeA.setEnabled(true);
            tCodice.setEnabled(true);
            break;
      }
   }

   /**
    * Mostra una descrizione di un errore SQL in un linguaggio comprensibile per
    * l'utente finale.
    * 
    * @param e eccezione SQLException catturata
    * @param query l'istruzione SQL che ha causato l'errore
    * @param contesto intero per distinguere se l'eccezione ha avuto origine
    * da una query
    */
   @Override
   protected void mostraErrori(SQLException e, String query, int contesto) {
      String msg;
      if (e.getErrorCode() == 1) {
         msg = "Esiste già un'altra ClasseDiAssociazione con lo stesso IdAss";
         JOptionPane.showMessageDialog(this, msg, "Errore",
                 JOptionPane.ERROR_MESSAGE);
      } else {
         super.mostraErrori(e, query, contesto);
      }
   }

   /**
    * Metodo da usare nei form di lookup per passare i dati al form
    * chiamante.
    */
   @Override
   protected void premutoOK() {
      if (getPadre() != null) {
          
         try {
            rs.close();
         } catch (SQLException e) {
            mostraErrori(e);
         }
         dispose();
      }
   }



   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jIdAss = new javax.swing.JLabel();
        jNomeA = new javax.swing.JLabel();
        tIdAss = new javax.swing.JTextField();
        spClasse_Di_Associazione = new javax.swing.JScrollPane();
        tabClasse_Di_Associazione = new javax.swing.JTable();
        jCodice = new javax.swing.JLabel();
        tNomeA = new javax.swing.JTextField();
        tCodice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Classe_Di_Associazione");
        setBackground(new java.awt.Color(102, 255, 255));
        setLocation(new java.awt.Point(640, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));

        jIdAss.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jIdAss.setForeground(new java.awt.Color(255, 255, 255));
        jIdAss.setText("IdAss");

        jNomeA.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jNomeA.setForeground(new java.awt.Color(255, 255, 255));
        jNomeA.setText("NomeA");

        tIdAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdAssActionPerformed(evt);
            }
        });

        tabClasse_Di_Associazione.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        spClasse_Di_Associazione.setViewportView(tabClasse_Di_Associazione);

        jCodice.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jCodice.setForeground(new java.awt.Color(255, 255, 255));
        jCodice.setText("Codice");

        tCodice.setText("Chiave Esterna ClassDiagram");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .add(spClasse_Di_Associazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 774, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(125, 125, 125))
            .add(jPanel1Layout.createSequentialGroup()
                .add(213, 213, 213)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jCodice)
                    .add(jNomeA)
                    .add(jIdAss))
                .add(67, 67, 67)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tIdAss)
                    .add(tNomeA)
                    .add(tCodice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 385, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jIdAss)
                    .add(tIdAss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNomeA)
                    .add(tNomeA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tCodice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCodice))
                .add(48, 48, 48)
                .add(spClasse_Di_Associazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tIdAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdAssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdAssActionPerformed

   /**
    * Ricopia i dati della riga selezionata del JTable
    * sugli altri controlli della finestra.
    */
   @Override
    protected void mostraDati() {
      try {
            rs.previous(); rs.next();
            tIdAss.setText(rs.getString("IdAss"));
            tNomeA.setText(rs.getString("NomeA"));
            tCodice.setText(rs.getString("Codice"));
         } catch (SQLException e) {
         mostraErrori(e);
      }
   }

   /**
    * Cancella i dati presenti in tutti i controlli presenti sul form.
    */
   @Override
    protected void pulisci() {
      super.pulisci();
        tIdAss.setText("");
        tNomeA.setText("");
        tCodice.setText("");
       
        
   }

   /**
    * Forma una query corrispondente ai dati inseriti nei
    * controlli della finestra.
    * 
    * @return query, come {@link PreparedStatement}
    */
   @Override
   protected PreparedStatement creaSelectStatement() {
      Connection con;
      PreparedStatement st;
      String   idass, nomea, codice;
      Pattern pat;
      Matcher matc;
      int k = 1;
      super.creaSelectStatement();
      idass = String.valueOf(tIdAss.getText());
      nomea = tNomeA.getText();
      codice = tCodice.getText();
     

      query += " where";
      //}
      if (idass.length() > 0) {
         query += " IdAss= ? and";
      }
      if (nomea.length() > 0) {
         if (nomea.contains("%")) {
            query += " NomeA like ? and";
         } else {
            query += " NomeA = ? and";
         }
      }
      if (codice.length() > 0) {
         if (codice.contains("%")) {
            query += " Codice like ? and";
         } else {
            query += " Codice = ? and";
         }
      }
      
      pat = Pattern.compile("where$|and$"); //cancella where o and finali
      matc = pat.matcher(query);
      query = matc.replaceAll("");
      try {
         con = Database.getDefaultConnection();
         st = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE,
                 ResultSet.CONCUR_READ_ONLY);

         if (idass.length() > 0) {
            st.setString(k++, idass);
         }
         if (nomea.length() > 0) {
            st.setString(k++, nomea);
         }
         if (codice.length() > 0) {
            st.setString(k++, codice);
         }
         
         return st;
      } catch (SQLException e) {
         mostraErrori(e);
         return null;
      }
   }

   /**
    * Prepara il comando SQL di inserimento in base ai dati
    * inseriti nei controlli.
    * 
    * @param c la connessione al DB
    * @return il comando, come {@link PreparedStatement}
    * @throws SQLException in caso di errori nel preparare il
    * comando
    */
   
   @Override
    protected PreparedStatement getComandoInserimento(Connection c)
        throws SQLException {
        String cmdIns;
        PreparedStatement st;
        cmdIns = "insert into " + Database.schema + ".Classe_Di_Associazione (IdAss,"
                + "NomeA,Codice)  values(?,?,?)";
        st = c.prepareStatement(cmdIns);
        st.setString(1, String.valueOf(tIdAss.getText()));
        st.setString(2, tNomeA.getText());
        st.setString(3, tCodice.getText());
        
        return st;
   }

   /**
    * Prepara il comando SQL di aggiornamento in base ai dati
    * inseriti nei controlli.
    * 
    * @param c la connessione al DB
    * @return il comando, come {@link PreparedStatement}
    * @throws SQLException in caso di errori nel preparare il
    * comando
    */
   
   @Override
    protected PreparedStatement getComandoAggiornamento ( Connection c) throws SQLException {
       String cmdUp;
       PreparedStatement st;
       cmdUp = "update " + Database.schema + ".Classe_Di_Associazione set NomeA=?,"
               + "Codice=? where IdAss=?";
       st = c.prepareStatement(cmdUp);
       st.setString(3, String.valueOf(tIdAss.getText()));
       st.setString(1, tNomeA.getText());
       st.setString(2, tCodice.getText());
      
       return st;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCodice;
    private javax.swing.JLabel jIdAss;
    private javax.swing.JLabel jNomeA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane spClasse_Di_Associazione;
    private javax.swing.JTextField tCodice;
    private javax.swing.JTextField tIdAss;
    private javax.swing.JTextField tNomeA;
    private javax.swing.JTable tabClasse_Di_Associazione;
    // End of variables declaration//GEN-END:variables



   @Override
   protected void getComandoElimina(Connection c)
    throws SQLException {
        String cmd;
        cmd = "delete from " + Database.schema + "." + "Classe_Di_Associazione"
               + " where IdAss=?";
        try {
            Connection conn = Database.getDefaultConnection();
            PreparedStatement st = conn.prepareStatement(cmd);
            st.setString(1, String.valueOf(tIdAss.getText()));
            st.executeUpdate();
            } catch (SQLException e) {
             mostraErrori(e);
        }     
   }
}