/*
 * DBFrame.java
 */
package database2019;

import java.sql.*;
import javax.swing.*;
import java.util.regex.*;

public class Dominio extends DBFrame {

   public Dominio() {
      super();
      initComponents();
      setModalita(INIZIO);
      setFrameTable(tabDominio);
      setNomeTabella("Dominio");
   }

   /**
    * Imposta lo stato corrente del form. <br> In base allo stato vengono
    * abilitati o disabilitati alcuni oggetti del form.
    * 
    * @param modo intero che rappresenta lo stato
    */
   @Override
   final public void setModalita(int modo) {
      super.setModalita(modo);
      switch (modo) {
          case INIZIO:
            tN_Parametri.setEnabled (false);
            tSegnatura.setEnabled(false);
            tCodiceP.setEnabled(false);
            break;
         case APPEND_QUERY:
            tN_Parametri.setEnabled (true);
            tSegnatura.setEnabled(true);
            tCodiceP.setEnabled(true);
            break;
         case BROWSE:
            tN_Parametri.setEnabled (false);
            tSegnatura.setEnabled(false);
            tCodiceP.setEnabled(false);
            break;
         case UPDATE:
            tN_Parametri.setEnabled (true);
            tSegnatura.setEnabled(false);
            tCodiceP.setEnabled(false);
            break;
      }
   }

   /**
    * Mostra una descrizione di un errore SQL in un linguaggio comprensibile per
    * l'utente finale.
    * 
    * @param e eccezione SQLException catturata
    * @param query l'istruzione SQL che ha causato l'errore
    * @param contesto intero per distinguere se l'eccezione ha avuto origine
    * da una query
    */
   @Override
   protected void mostraErrori(SQLException e, String query, int contesto) {
      String msg;
      if (e.getErrorCode() == 1) {
         msg = "Esiste già un'altro Dominio ";
         JOptionPane.showMessageDialog(this, msg, "Errore",
         JOptionPane.ERROR_MESSAGE);
      } else {
         super.mostraErrori(e, query, contesto);
      }
   }

   /**
    * Metodo da usare nei form di lookup per passare i dati al form
    * chiamante.
    */
   @Override
   protected void premutoOK() {
      if (getPadre() != null) {
         try {
            rs.close();
         } catch (SQLException e) {
            mostraErrori(e);
         }
         dispose();
      }
   }



   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jN_Parametri = new javax.swing.JLabel();
        jSegnatura = new javax.swing.JLabel();
        tN_Parametri = new javax.swing.JTextField();
        spDominio = new javax.swing.JScrollPane();
        tabDominio = new javax.swing.JTable();
        jCodiceP = new javax.swing.JLabel();
        tSegnatura = new javax.swing.JTextField();
        tCodiceP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dominio");
        setBackground(new java.awt.Color(102, 255, 255));
        setLocation(new java.awt.Point(640, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));

        jN_Parametri.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jN_Parametri.setForeground(new java.awt.Color(255, 255, 255));
        jN_Parametri.setText("N_Parametri");

        jSegnatura.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jSegnatura.setForeground(new java.awt.Color(255, 255, 255));
        jSegnatura.setText("Segnatura");

        tN_Parametri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tN_ParametriActionPerformed(evt);
            }
        });

        tabDominio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        spDominio.setViewportView(tabDominio);

        jCodiceP.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jCodiceP.setForeground(new java.awt.Color(255, 255, 255));
        jCodiceP.setText("Codicep");

        tSegnatura.setText("Chiave Esterna Metodo");

        tCodiceP.setText("Chiave Esterna Parametro");
        tCodiceP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodicePActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(91, 91, 91)
                        .add(spDominio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 843, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(204, 204, 204)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jCodiceP)
                            .add(jSegnatura)
                            .add(jN_Parametri))
                        .add(67, 67, 67)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(tN_Parametri)
                            .add(tSegnatura)
                            .add(tCodiceP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 385, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jN_Parametri)
                    .add(tN_Parametri, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jSegnatura)
                    .add(tSegnatura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tCodiceP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCodiceP))
                .add(38, 38, 38)
                .add(spDominio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 272, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tN_ParametriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tN_ParametriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tN_ParametriActionPerformed

    private void tCodicePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodicePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodicePActionPerformed

   /**
    * Ricopia i dati della riga selezionata del JTable
    * sugli altri controlli della finestra.
    */
   @Override
    protected void mostraDati() {
      try {
            rs.previous(); rs.next();
            tN_Parametri.setText(rs.getString("N_Parametri"));
            tSegnatura.setText(rs.getString("Segnatura"));
            tCodiceP.setText(rs.getString("CodiceP"));
            
			
        
      } catch (SQLException e) {
         mostraErrori(e);
      }
   }

   /**
    * Cancella i dati presenti in tutti i controlli presenti sul form.
    */
   @Override
    protected void pulisci() {
      super.pulisci();
        tN_Parametri.setText("");
        tSegnatura.setText("");
        tCodiceP.setText("");
        
        
   }

   /**
    * Forma una query corrispondente ai dati inseriti nei
    * controlli della finestra.
    * 
    * @return query, come {@link PreparedStatement}
    */
   @Override
   protected PreparedStatement creaSelectStatement() {
      Connection con;
      PreparedStatement st;
      String   n_parametri, segnatura, codicep;
      Pattern pat;
      Matcher matc;
      int k = 1;
      super.creaSelectStatement();
      n_parametri = String.valueOf(tN_Parametri.getText());
      segnatura = tSegnatura.getText();
      codicep = String.valueOf(tCodiceP.getText());
      

      query += " where";
      //}
      if (n_parametri.length() > 0) {
		  if (n_parametri.contains("%")) {
            query += " N_Parametri like ? and";
         } else {
            query += " N_Parametri= ? and";
         }
      }
      if (segnatura.length() > 0) {
         if (segnatura.contains("%")) {
            query += " Segnatura like ? and";
         } else {
            query += " Segnatura = ? and";
         }
      }
      if (codicep.length() > 0) {
         if (codicep.contains("%")) {
            query += " CodiceP like ? and";
         } else {
            query += " CodiceP= ? and";
         }
      }
     
      pat = Pattern.compile("where$|and$"); //cancella where o and finali
      matc = pat.matcher(query);
      query = matc.replaceAll("");
      try {
         con = Database.getDefaultConnection();
         st = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE,
                 ResultSet.CONCUR_READ_ONLY);

         if (n_parametri.length() > 0) {
            st.setString(k++, n_parametri);
         }
         if (segnatura.length() > 0) {
            st.setString(k++, segnatura);
         }
         if (codicep.length() > 0) {
            st.setString(k++, codicep);
         }
         
         return st;
      } catch (SQLException e) {
         mostraErrori(e);
         return null;
      }
   }

   /**
    * Prepara il comando SQL di inserimento in base ai dati
    * inseriti nei controlli.
    * 
    * @param c la connessione al DB
    * @return il comando, come {@link PreparedStatement}
    * @throws SQLException in caso di errori nel preparare il
    * comando
    */
   
   @Override
    protected PreparedStatement getComandoInserimento(Connection c)
        throws SQLException {
        String cmdIns;
        PreparedStatement st;
        cmdIns = "insert into " + Database.schema + ".Dominio (N_Parametri,"
                + "Segnatura,CodiceP)  values(?,?,?)";
        st = c.prepareStatement(cmdIns);
        st.setString(1, String.valueOf(tN_Parametri.getText()));
        st.setString(2, tSegnatura.getText());
        st.setString(3, String.valueOf(tCodiceP.getText()));
        
        return st;
   }

   /**
    * Prepara il comando SQL di aggiornamento in base ai dati
    * inseriti nei controlli.
    * 
    * @param c la connessione al DB
    * @return il comando, come {@link PreparedStatement}
    * @throws SQLException in caso di errori nel preparare il
    * comando
    */
   
   @Override
    protected PreparedStatement getComandoAggiornamento ( Connection c) throws SQLException {
       String cmdUp;
       PreparedStatement st;
       cmdUp = "update " + Database.schema + ".Dominio set N_Parametri=?,Segnatura=?,CodiceP=?" 
             + " where Segnatura=? or CodiceP=?" ; 
       st = c.prepareStatement(cmdUp);
       st.setString(5, String.valueOf(tCodiceP.getText()));
       st.setString(4, tSegnatura.getText());
       st.setString(1, String.valueOf(tN_Parametri.getText()));
       st.setString(2, tSegnatura.getText());
       st.setString(3, String.valueOf(tCodiceP.getText()));
       
       return st;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCodiceP;
    private javax.swing.JLabel jN_Parametri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSegnatura;
    private javax.swing.JScrollPane spDominio;
    private javax.swing.JTextField tCodiceP;
    private javax.swing.JTextField tN_Parametri;
    private javax.swing.JTextField tSegnatura;
    private javax.swing.JTable tabDominio;
    // End of variables declaration//GEN-END:variables



   @Override
   protected void getComandoElimina(Connection c)
    throws SQLException {
        String cmd;
        cmd = "delete from " + Database.schema + "." + "Dominio"
               + " where Segnatura=? and  CodiceP=?" ;
        try {
            Connection conn = Database.getDefaultConnection();
            PreparedStatement st = conn.prepareStatement(cmd);
            st.setString(1, tSegnatura.getText());
            st.setString(2, tCodiceP.getText());
	  
            st.executeUpdate();
            } catch (SQLException e) {
             mostraErrori(e);
        }     
   }
}