
package database2019;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


public class Login extends javax.swing.JDialog {

    /**
     * Costante per indicare la pressione del pulsante Annulla.
     */
    public static final int PREMUTO_ANNULLA = 0;
    /**
     * Costante per indicare la pressione del pulsante OK.
     */
    public static final int PREMUTO_LOGIN = 1;
    
    private int premuto; // registra quale pulsante viene premuto
    
    /*
     * Listener sul contenuto della casella Utente (tUser), utilizzato quando
     * la relativa checkbox è spuntata. DocumentListener è un'interfaccia:
     * per costruire un tale oggetto implementiamo di seguito i suoi metodi.
     */
    private final DocumentListener cambioTestoUser = new DocumentListener() {
        /**
         * Metodo del listener per sostituzioni di testo.
         * 
         * @param e evento di sostituzione testo
         */
        @Override
        public void changedUpdate(DocumentEvent e) {
            setSchemaToUser();
        }

        /**
         * Metodo del listener per rimozioni di testo.
         * 
         * @param e evento di rimozione testo
         */
        @Override
        public void removeUpdate(DocumentEvent e) {
            setSchemaToUser();
        }

        /**
         * Metodo del listener per inserimenti di testo.
         * 
         * @param e evento di inserimento testo
         */
        @Override
        public void insertUpdate(DocumentEvent e) {
            setSchemaToUser();
        }

        private void setSchemaToUser() { // imposta Schema = Utente
            tSchema.setText(tUser.getText());
        }
    }; 

   /**
    * Restituisce il contenuto del campo premuto, che
    * rappresenta il pulsante premuto dall'utente.
    *
    * @return intero che descrive il pulsante premuto
    */
    public int getPremuto() {
       return premuto;
    }
   
    /*
     * Imposta il pulsante di default accessibile con Enter.
     * Metodo privato, quindi non overridable (cosa buona
     * per metodi richiamati dai costruttori)
     */
    private void impostaDefault() {
       getRootPane().setDefaultButton(bLogin);
    }

    /**
     * Costruisce la finestra tenendo traccia del frame chiamante.
     *
     * @param parent Frame chiamante
     * @param modal Specifica se la finestra di dialogo blocca l'input utente
     * sulla finestra chiamante
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tUser.requestFocus();
        impostaDefault();
        
        // Listen for changes in the text
        tUser.getDocument().addDocumentListener(cambioTestoUser);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Background();
        checkSchema = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        bAnnulla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tPorta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tServizio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tSchema = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(640, 480));
        setResizable(false);

        checkSchema.setSelected(true);
        checkSchema.setText("=Utente");
        checkSchema.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkSchemaItemStateChanged(evt);
            }
        });
        checkSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSchemaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Utente");

        tUser.setText("system");
        tUser.setToolTipText("");
        tUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        tPassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tPassword.setPreferredSize(new java.awt.Dimension(30, 20));

        bLogin.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bLogin.setForeground(new java.awt.Color(0, 51, 153));
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bAnnulla.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bAnnulla.setForeground(new java.awt.Color(255, 0, 0));
        bAnnulla.setText("Annulla");
        bAnnulla.setDefaultCapable(false);
        bAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnullaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Host");

        tHost.setText("localhost");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Porta");

        tPorta.setText("1521");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Servizio");

        tServizio.setText("XE");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Schema");

        tSchema.setText("system");
        tSchema.setEnabled(false);
        tSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSchemaActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bAnnulla)
                                .addGap(57, 57, 57)
                                .addComponent(bLogin)
                                .addGap(22, 22, 22))
                            .addComponent(tServizio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(tSchema)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(checkSchema)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(tHost, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel6)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tServizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSchema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin)
                    .addComponent(bAnnulla))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        Database.host = tHost.getText();
        try {
            Database.porta = Integer.parseInt(tPorta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La porta dev'essere"
                + " un numero", "Errore", JOptionPane.ERROR_MESSAGE);
        }
        Database.schema = tSchema.getText();
        Database.servizio = tServizio.getText();
        Database.user = tUser.getText();
        Database.password = new String(tPassword.getPassword());
        try {
            Database.setDefaultConnection(Database.nuovaConnessione());
            premuto = PREMUTO_LOGIN;
            dispose();
        } catch (SQLException e) {
            // Database.mostraErroriSwing(this, e);
            JOptionPane.showMessageDialog(this, "Connessione fallita (credenziali"
                + " errate?)", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
        premuto = PREMUTO_ANNULLA;
        dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed

    private void checkSchemaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkSchemaItemStateChanged
        if (checkSchema.isSelected()) {
            tSchema.setEnabled(false);
            tUser.getDocument().addDocumentListener(cambioTestoUser);
            tSchema.setText(tUser.getText());
        } else {
            tSchema.setEnabled(true);
            tUser.getDocument().removeDocumentListener(cambioTestoUser);
        }
    }//GEN-LAST:event_checkSchemaItemStateChanged

    private void tUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserActionPerformed

    private void checkSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSchemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSchemaActionPerformed

    private void tSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSchemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSchemaActionPerformed

    /**
     * Non utilizzato: Login non funziona da classe principale. Il metodo main
     * in questo progetto è {@link Principale#main(java.lang.String[])}
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox checkSchema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tHost;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tPorta;
    private javax.swing.JTextField tSchema;
    private javax.swing.JTextField tServizio;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
