/*
 * DBFrame.java
 */
package database2019;

import java.sql.*;
import javax.swing.*;
import java.util.regex.*;

public class Parametro extends DBFrame {

   public Parametro() {
      super();
      initComponents();
      setModalita(INIZIO);
      setFrameTable(tabParametro);
      setNomeTabella("Parametro");
   }

   /**
    * Imposta lo stato corrente del form. <br> In base allo stato vengono
    * abilitati o disabilitati alcuni oggetti del form.
    * 
    * @param modo intero che rappresenta lo stato
    */
   @Override
   final public void setModalita(int modo) {
      super.setModalita(modo);
      switch (modo) {
          case INIZIO:
            tCodiceP.setEnabled (false);
            tNomeP.setEnabled(false);
            tCodiceT.setEnabled(false);
            tP_IN.setEnabled(false);
            tP_OUT.setEnabled(false);
            break;
         case APPEND_QUERY:
            tCodiceP.setEnabled (true);
            tNomeP.setEnabled(true);
            tCodiceT.setEnabled(true);
            tP_IN.setEnabled(true);
            tP_OUT.setEnabled(true);
            break;
         case BROWSE:
            tCodiceP.setEnabled (false);
            tNomeP.setEnabled(false);
            tCodiceT.setEnabled(false);
            tP_IN.setEnabled(false);
            tP_OUT.setEnabled(false);
            break;
         case UPDATE:
            tCodiceP.setEnabled (false);
            tNomeP.setEnabled(true);
            tCodiceT.setEnabled(true);
            tP_IN.setEnabled(true);
            tP_OUT.setEnabled(true);
            break;
      }
   }

   /**
    * Mostra una descrizione di un errore SQL in un linguaggio comprensibile per
    * l'utente finale.
    * 
    * @param e eccezione SQLException catturata
    * @param query l'istruzione SQL che ha causato l'errore
    * @param contesto intero per distinguere se l'eccezione ha avuto origine
    * da una query
    */
   @Override
   protected void mostraErrori(SQLException e, String query, int contesto) {
      String msg;
      if (e.getErrorCode() == 1) {
         msg = "Esiste già un'altro Parametro con lo stesso CodiceP";
         JOptionPane.showMessageDialog(this, msg, "Errore",
                 JOptionPane.ERROR_MESSAGE);
      } else {
         super.mostraErrori(e, query, contesto);
      }
   }

   /**
    * Metodo da usare nei form di lookup per passare i dati al form
    * chiamante.
    */
   @Override
   protected void premutoOK() {
      if (getPadre() != null) {
         try {
            rs.close();
         } catch (SQLException e) {
            mostraErrori(e);
         }
         dispose();
      }
   }



   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCodiceP = new javax.swing.JLabel();
        jNomeP = new javax.swing.JLabel();
        tCodiceP = new javax.swing.JTextField();
        spParametro = new javax.swing.JScrollPane();
        tabParametro = new javax.swing.JTable();
        jCodiceT = new javax.swing.JLabel();
        tNomeP = new javax.swing.JTextField();
        tCodiceT = new javax.swing.JTextField();
        jP_IN = new javax.swing.JLabel();
        jP_OUT = new javax.swing.JLabel();
        tP_IN = new javax.swing.JTextField();
        tP_OUT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametro");
        setBackground(new java.awt.Color(102, 255, 255));
        setLocation(new java.awt.Point(640, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));

        jCodiceP.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jCodiceP.setForeground(new java.awt.Color(255, 255, 255));
        jCodiceP.setText("CodiceP");

        jNomeP.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jNomeP.setForeground(new java.awt.Color(255, 255, 255));
        jNomeP.setText("NomeP");

        tCodiceP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodicePActionPerformed(evt);
            }
        });

        tabParametro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null,null,null},
                {null, null, null,null,null},
                {null, null, null,null,null},
                {null, null, null,null,null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        spParametro.setViewportView(tabParametro);

        jCodiceT.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jCodiceT.setForeground(new java.awt.Color(255, 255, 255));
        jCodiceT.setText("CodiceT");

        tCodiceT.setText("Chiave Esterna Tipo");
        tCodiceT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodiceTActionPerformed(evt);
            }
        });

        jP_IN.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jP_IN.setForeground(new java.awt.Color(255, 255, 255));
        jP_IN.setText("P_IN");

        jP_OUT.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jP_OUT.setForeground(new java.awt.Color(255, 255, 255));
        jP_OUT.setText("P_OUT");

        tP_IN.setText("1 se è un parametro di input, 0 altrimenti");

        tP_OUT.setText("1 se è un parametro di output, 0 altrimenti");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(231, 231, 231)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jP_OUT)
                    .add(jP_IN)
                    .add(jCodiceT)
                    .add(jNomeP)
                    .add(jCodiceP))
                .add(67, 67, 67)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tCodiceP)
                    .add(tNomeP)
                    .add(tCodiceT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .add(tP_IN)
                    .add(tP_OUT))
                .addContainerGap(290, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(spParametro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 863, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCodiceP)
                    .add(tCodiceP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNomeP)
                    .add(tNomeP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCodiceT)
                    .add(tCodiceT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jP_IN)
                    .add(tP_IN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jP_OUT)
                    .add(tP_OUT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(spParametro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCodicePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodicePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodicePActionPerformed

    private void tCodiceEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tCodiceTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodiceTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodiceTActionPerformed

   /**
    * Ricopia i dati della riga selezionata del JTable
    * sugli altri controlli della finestra.
    */
   @Override
    protected void mostraDati() {
      try {
            rs.previous(); rs.next();
            tCodiceP.setText(rs.getString("CodiceP"));
            tNomeP.setText(rs.getString("NomeP"));
            tCodiceT.setText(rs.getString("CodiceT"));
            tP_IN.setText(rs.getString("P_IN"));
            tP_OUT.setText(rs.getString("P_OUT"));
			
        
      } catch (SQLException e) {
         mostraErrori(e);
      }
   }

   /**
    * Cancella i dati presenti in tutti i controlli presenti sul form.
    */
   @Override
    protected void pulisci() {
      super.pulisci();
        tCodiceP.setText("");
        tNomeP.setText("");
        tCodiceT.setText("");
        tP_IN.setText("");
        tP_OUT.setText("");
        
   }

   /**
    * Forma una query corrispondente ai dati inseriti nei
    * controlli della finestra.
    * 
    * @return query, come {@link PreparedStatement}
    */
   @Override
   protected PreparedStatement creaSelectStatement() {
      Connection con;
      PreparedStatement st;
      String   codicep, nomep, codicet, p_in, p_out;
      Pattern pat;
      Matcher matc;
      int k = 1;
      super.creaSelectStatement();
      codicep = String.valueOf(tCodiceP.getText());
      nomep = tNomeP.getText();
      codicet = String.valueOf(tCodiceT.getText());
      p_in = String.valueOf(tP_IN.getText());
      p_out = String.valueOf(tP_OUT.getText());

      query += " where";
      //}
      if (codicep.length() > 0) {
         query += " CodiceP= ? and";
      }
      if (nomep.length() > 0) {
         if (nomep.contains("%")) {
            query += " NomeP like ? and";
         } else {
            query += " NomeP = ? and";
         }
      }
      if (codicet.length() > 0) {
         if (codicet.contains("%")) {
            query += " CodiceT like ? and";
         } else {
            query += " CodiceT = ? and";
         }
      }
      if (p_in.length() > 0) {
         if (p_in.contains("%")) {
            query += " P_IN like ? and";
         } else {
            query += " P_IN = ? and";
         }
      }
      if (p_out.length() > 0) {
         if (p_out.contains("%")) {
            query += " P_OUT like ? and";
         } else {
            query += " P_OUT = ? and";
         }
      }
      pat = Pattern.compile("where$|and$"); //cancella where o and finali
      matc = pat.matcher(query);
      query = matc.replaceAll("");
      try {
         con = Database.getDefaultConnection();
         st = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE,
                 ResultSet.CONCUR_READ_ONLY);

         if (codicep.length() > 0) {
            st.setString(k++, codicep);
         }
         if (nomep.length() > 0) {
            st.setString(k++, nomep);
         }
         if (codicet.length() > 0) {
            st.setString(k++, codicet);
         }
         if (p_in.length() > 0) {
            st.setString(k++, p_in);
         }
         if (p_out.length() > 0) {
            st.setString(k++, p_out);
         }
         return st;
      } catch (SQLException e) {
         mostraErrori(e);
         return null;
      }
   }

   /**
    * Prepara il comando SQL di inserimento in base ai dati
    * inseriti nei controlli.
    * 
    * @param c la connessione al DB
    * @return il comando, come {@link PreparedStatement}
    * @throws SQLException in caso di errori nel preparare il
    * comando
    */
   
   @Override
    protected PreparedStatement getComandoInserimento(Connection c)
        throws SQLException {
        String cmdIns;
        PreparedStatement st;
        cmdIns = "insert into " + Database.schema + ".Parametro(CodiceP,NomeP,"
                + "CodiceT,P_IN,P_OUT) values(?,?,?,?,?)";
        st = c.prepareStatement(cmdIns);
        st.setString(1, String.valueOf(tCodiceP.getText()));
        st.setString(2, tNomeP.getText());
        st.setString(3, String.valueOf(tCodiceT.getText()));
        st.setString(4, String.valueOf(tP_IN.getText()));
        st.setString(5, String.valueOf(tP_OUT.getText ()));
        return st;
   }

   /**
    * Prepara il comando SQL di aggiornamento in base ai dati
    * inseriti nei controlli.
    * 
    * @param c la connessione al DB
    * @return il comando, come {@link PreparedStatement}
    * @throws SQLException in caso di errori nel preparare il
    * comando
    */
   
   @Override
    protected PreparedStatement getComandoAggiornamento ( Connection c) throws SQLException {
       String cmdUp;
       PreparedStatement st;
       cmdUp = "update " + Database.schema + ".Parametro set NomeP=?,CodiceT=?,"
               + "P_IN=?,P_OUT=? where CodiceP=?" ;
       st = c.prepareStatement(cmdUp);
       st.setString(5, String.valueOf(tCodiceP.getText()));
       st.setString(1, tNomeP.getText());
       st.setString(2, String.valueOf(tCodiceT.getText()));
       st.setString(3, String.valueOf(tP_IN.getText()));
       st.setString(4, String.valueOf(tP_OUT.getText()));
       return st;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCodiceP;
    private javax.swing.JLabel jCodiceT;
    private javax.swing.JLabel jNomeP;
    private javax.swing.JLabel jP_IN;
    private javax.swing.JLabel jP_OUT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane spParametro;
    private javax.swing.JTextField tCodiceP;
    private javax.swing.JTextField tCodiceT;
    private javax.swing.JTextField tNomeP;
    private javax.swing.JTextField tP_IN;
    private javax.swing.JTextField tP_OUT;
    private javax.swing.JTable tabParametro;
    // End of variables declaration//GEN-END:variables



   @Override
   protected void getComandoElimina(Connection c)
    throws SQLException {
        String cmd;
        cmd = "delete from " + Database.schema + "." + "Parametro"
               + " where CodiceP=?";
        try {
            Connection conn = Database.getDefaultConnection();
            PreparedStatement st = conn.prepareStatement(cmd);
            st.setString(1, tCodiceP.getText());
            st.executeUpdate();
            } catch (SQLException e) {
             mostraErrori(e);
        }     
   }
}