/*
 * Principale.java
 */
package database2019;

import javax.swing.JOptionPane;

/**
 * Finestra principale dell'applicazione; permette di scegliere
 * fra le tabelle da gestire.
 */
public class Principale extends javax.swing.JFrame {

   /**
    * Crea nuova finestra Principale.
    */
   public Principale() {
      initComponents();
      loginOrExit();
   }

   private void loginOrExit() {
      Login l = new Login(this, true);
      l.setVisible(true);
      if (l.getPremuto() == Login.PREMUTO_ANNULLA) {
         dispose();
      } else {
         setVisible(true);
      }
   }
   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form
    * Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bClassDiagram = new javax.swing.JButton();
        bComponimento = new javax.swing.JButton();
        bTipo = new javax.swing.JButton();
        bPartecipa = new javax.swing.JButton();
        bParametro = new javax.swing.JButton();
        bDominio = new javax.swing.JButton();
        bAttributo = new javax.swing.JButton();
        bClasse = new javax.swing.JButton();
        bCommento = new javax.swing.JButton();
        bClasse_Di_Associazione = new javax.swing.JButton();
        bMetodo = new javax.swing.JButton();
        bValore = new javax.swing.JButton();
        bAssociazione = new javax.swing.JButton();
        bEnumeration = new javax.swing.JButton();
        bChiave_Esterna = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miLogin = new javax.swing.JMenuItem();
        miEsci = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        miInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principale");
        setLocation(new java.awt.Point(640, 150));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        bClassDiagram.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bClassDiagram.setForeground(new java.awt.Color(0, 51, 153));
        bClassDiagram.setMnemonic('M');
        bClassDiagram.setText("ClassDiagram");
        bClassDiagram.setFocusable(false);
        bClassDiagram.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bClassDiagram.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bClassDiagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClassDiagramActionPerformed(evt);
            }
        });

        bComponimento.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bComponimento.setForeground(new java.awt.Color(0, 51, 153));
        bComponimento.setText("Componimento");
        bComponimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComponimentoActionPerformed(evt);
            }
        });

        bTipo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bTipo.setForeground(new java.awt.Color(0, 51, 153));
        bTipo.setText("Tipo");
        bTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTipoActionPerformed(evt);
            }
        });

        bPartecipa.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bPartecipa.setForeground(new java.awt.Color(0, 51, 153));
        bPartecipa.setText("Partecipa");
        bPartecipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPartecipaActionPerformed(evt);
            }
        });

        bParametro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bParametro.setForeground(new java.awt.Color(0, 51, 153));
        bParametro.setText("Parametro");
        bParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParametroActionPerformed(evt);
            }
        });

        bDominio.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bDominio.setForeground(new java.awt.Color(0, 51, 153));
        bDominio.setText("Dominio");
        bDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDominioActionPerformed(evt);
            }
        });

        bAttributo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bAttributo.setForeground(new java.awt.Color(0, 51, 153));
        bAttributo.setText("Attributo");
        bAttributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAttributoActionPerformed(evt);
            }
        });

        bClasse.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bClasse.setForeground(new java.awt.Color(0, 51, 153));
        bClasse.setText("Classe");
        bClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClasseActionPerformed(evt);
            }
        });

        bCommento.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bCommento.setForeground(new java.awt.Color(0, 51, 153));
        bCommento.setText("Commento");
        bCommento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCommentoActionPerformed(evt);
            }
        });

        bClasse_Di_Associazione.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bClasse_Di_Associazione.setForeground(new java.awt.Color(0, 51, 153));
        bClasse_Di_Associazione.setText("Classe_Di_Associazione");
        bClasse_Di_Associazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClasse_Di_AssociazioneActionPerformed(evt);
            }
        });

        bMetodo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bMetodo.setForeground(new java.awt.Color(0, 51, 153));
        bMetodo.setText("Metodo");
        bMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMetodoActionPerformed(evt);
            }
        });

        bValore.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bValore.setForeground(new java.awt.Color(0, 51, 153));
        bValore.setText("Valore");
        bValore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValoreActionPerformed(evt);
            }
        });

        bAssociazione.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bAssociazione.setForeground(new java.awt.Color(0, 51, 153));
        bAssociazione.setText("Associazione");
        bAssociazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAssociazioneActionPerformed(evt);
            }
        });

        bEnumeration.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bEnumeration.setForeground(new java.awt.Color(0, 51, 153));
        bEnumeration.setText("Enumeration");
        bEnumeration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnumerationActionPerformed(evt);
            }
        });

        bChiave_Esterna.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        bChiave_Esterna.setForeground(new java.awt.Color(255, 0, 0));
        bChiave_Esterna.setText("Chiave_Esterna");
        bChiave_Esterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChiave_EsternaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bAssociazione, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCommento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bComponimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bClassDiagram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bClasse_Di_Associazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPartecipa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAttributo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bChiave_Esterna, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(bDominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bValore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEnumeration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bEnumeration)
                                .addComponent(bPartecipa))
                            .addComponent(bClassDiagram)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bComponimento)
                            .addComponent(bClasse)
                            .addComponent(bParametro))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCommento)
                    .addComponent(bAttributo)
                    .addComponent(bValore))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAssociazione)
                    .addComponent(bMetodo)
                    .addComponent(bDominio))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClasse_Di_Associazione)
                    .addComponent(bTipo)
                    .addComponent(bChiave_Esterna))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        menuFile.setMnemonic('F');
        menuFile.setText("File");

        miLogin.setMnemonic('L');
        miLogin.setText("Login");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        menuFile.add(miLogin);

        miEsci.setMnemonic('E');
        miEsci.setText("Esci");
        miEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEsciActionPerformed(evt);
            }
        });
        menuFile.add(miEsci);

        jMenuBar1.add(menuFile);

        menuHelp.setMnemonic('A');
        menuHelp.setText("Aiuto");

        miInfo.setMnemonic('I');
        miInfo.setText("Informazioni su…");
        miInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInfoActionPerformed(evt);
            }
        });
        menuHelp.add(miInfo);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void bClassDiagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClassDiagramActionPerformed
      ClassDiagram m;
      m = new ClassDiagram();
      m.setVisible(true);
   }//GEN-LAST:event_bClassDiagramActionPerformed

   private void miEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEsciActionPerformed
      dispose();
   }//GEN-LAST:event_miEsciActionPerformed

   private void miInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInfoActionPerformed
      JOptionPane.showMessageDialog(this,
              "Applicazione Java del Corso di Basi di dati e sist. inf. I"
                      + "\nUniversità di Napoli Federico II" 
                      + "\n\nSviluppato da G. Di Luca e C. Di Martino",
              "Informazioni su", JOptionPane.INFORMATION_MESSAGE);
   }//GEN-LAST:event_miInfoActionPerformed

   private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
       Login l;
       l = new Login(this, true);
       l.setVisible(true);
       if (l.getPremuto() == Login.PREMUTO_ANNULLA) {
          dispose();
       }
   }//GEN-LAST:event_miLoginActionPerformed

    private void bClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClasseActionPerformed
        Classe m;
        m = new Classe();
        m.setVisible(true);
    }//GEN-LAST:event_bClasseActionPerformed

    private void bCommentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCommentoActionPerformed
        Commento m;
        m = new Commento();
        m.setVisible(true);
    }//GEN-LAST:event_bCommentoActionPerformed

    private void bMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMetodoActionPerformed
        Metodo m;
        m = new Metodo();
        m.setVisible(true);
    }//GEN-LAST:event_bMetodoActionPerformed

    private void bParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParametroActionPerformed
        Parametro m;
        m = new Parametro();
        m.setVisible(true);
    }//GEN-LAST:event_bParametroActionPerformed

    private void bAttributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAttributoActionPerformed
        Attributo m;
        m = new Attributo();
        m.setVisible(true);
    }//GEN-LAST:event_bAttributoActionPerformed

    private void bAssociazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAssociazioneActionPerformed
        Associazione m;
        m = new Associazione();
        m.setVisible(true);
    }//GEN-LAST:event_bAssociazioneActionPerformed

    private void bTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTipoActionPerformed
        Tipo m;
        m = new Tipo();
        m.setVisible(true);
    }//GEN-LAST:event_bTipoActionPerformed

    private void bPartecipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPartecipaActionPerformed
        Partecipa m;
        m = new Partecipa();
        m.setVisible(true);
    }//GEN-LAST:event_bPartecipaActionPerformed

    private void bClasse_Di_AssociazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClasse_Di_AssociazioneActionPerformed
        Classe_Di_Associazione m;
        m = new Classe_Di_Associazione();
        m.setVisible(true);
    }//GEN-LAST:event_bClasse_Di_AssociazioneActionPerformed

    private void bEnumerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnumerationActionPerformed
        Enumeration m;
        m = new Enumeration();
        m.setVisible(true);
    }//GEN-LAST:event_bEnumerationActionPerformed

    private void bValoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValoreActionPerformed
        Valore m;
        m = new Valore();
        m.setVisible(true);
    }//GEN-LAST:event_bValoreActionPerformed

    private void bComponimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComponimentoActionPerformed
        Componimento m;
        m = new Componimento();
        m.setVisible(true);
    }//GEN-LAST:event_bComponimentoActionPerformed

    private void bDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDominioActionPerformed
        Dominio m;
        m = new Dominio();
        m.setVisible(true);
    }//GEN-LAST:event_bDominioActionPerformed

    private void bChiave_EsternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChiave_EsternaActionPerformed
        Chiave_Esterna m;
        m = new Chiave_Esterna();
        m.setVisible(true);
    }//GEN-LAST:event_bChiave_EsternaActionPerformed

   /**
    * Lancia il thread di gestione eventi.
    * 
    * @param args the command line arguments
    */
   public static void main(String args[]) {

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            Principale p = new Principale();
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAssociazione;
    private javax.swing.JButton bAttributo;
    private javax.swing.JButton bChiave_Esterna;
    private javax.swing.JButton bClassDiagram;
    private javax.swing.JButton bClasse;
    private javax.swing.JButton bClasse_Di_Associazione;
    private javax.swing.JButton bCommento;
    private javax.swing.JButton bComponimento;
    private javax.swing.JButton bDominio;
    private javax.swing.JButton bEnumeration;
    private javax.swing.JButton bMetodo;
    private javax.swing.JButton bParametro;
    private javax.swing.JButton bPartecipa;
    private javax.swing.JButton bTipo;
    private javax.swing.JButton bValore;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem miEsci;
    private javax.swing.JMenuItem miInfo;
    private javax.swing.JMenuItem miLogin;
    // End of variables declaration//GEN-END:variables
}
